"""The DOM/CSS over-reporting gate: planted cases the wired pipeline must get right.

  shared-counter        written by two fixture modules       -> multi_writer_element
  bound-counter         two functions in ONE module write it -> multi_writer_element
  purchase-btn          in the template, styled by CSS       -> no unresolved edge
  no-such-class-anywhere  a CSS rule nothing uses            -> UNUSED (both sides visible)
  --dead-token          declared, never consumed             -> UNUSED
  --used-token          declared and consumed                -> CONNECTED
  bg-slate-900          generated by the utility build       -> never UNRESOLVED
"""

import collections
from pathlib import Path

from django.test import SimpleTestCase

from seamcheck.graph import Status
from seamcheck.pipeline import run_scan

FIXTURES = Path(__file__).parent / "fixtures"


class DomCssRegressionGateTests(SimpleTestCase):
    def setUp(self):
        self.graph = run_scan(
            urlconf_module="seamcheck.tests.fixtures.fixture_urls",
            js_entry_files=[
                str(FIXTURES / "fixture_dom_multiwriter_a.js"),
                str(FIXTURES / "fixture_dom_multiwriter_b.js"),
                str(FIXTURES / "fixture_dom_single_writer.js"),
            ],
            js_project_root=str(FIXTURES),
            template_files=[str(FIXTURES / "fixture_dom_template.html")],
            css_files=[str(FIXTURES / "fixture_dom.css")],
            tailwind_build_classes={"bg-slate-900"},
        )
        self.by_kind = {}
        for symbol in self.graph.symbols:
            self.by_kind.setdefault(symbol.kind, []).append(symbol)

    def test_the_two_writer_element_is_flagged(self):
        # Two findings, and they are deliberately different strengths. `shared-counter`
        # is written from two FILES: whichever loads last wins, and that is UNRESOLVED.
        # `bound-counter` is written from two functions in ONE file - once through a
        # local, once through `this` - which used to be invisible because the gate asked
        # for two distinct files, and is the exact shape of a display bug that comes back
        # after being "fixed" in one of them. One module writing an element from a setup
        # path and an update path is ordinary until a person looks, so it is a lead:
        # UNCERTAIN, naming the two functions rather than two files.
        flagged = {s.label: s for s in self.by_kind.get("multi_writer_element", [])}

        self.assertEqual(sorted(flagged), ["bound-counter", "shared-counter"])
        self.assertEqual(flagged["shared-counter"].status, Status.UNRESOLVED)
        self.assertEqual(flagged["bound-counter"].status, Status.UNCERTAIN)
        for label, symbol in flagged.items():
            self.assertGreaterEqual(len(symbol.chain), 2, label)

    def test_the_single_writer_element_is_not_flagged(self):
        flagged = {s.label for s in self.by_kind.get("multi_writer_element", [])}

        self.assertNotIn("gift-btn", flagged)

    def test_a_css_rule_nothing_references_is_reported_unused(self):
        # Both sides are observable here - the template set and the CSS set - so UNUSED
        # is an evidence-backed claim, unlike a page URL.
        unused = {
            e.from_id for e in self.graph.edges if e.status is Status.UNUSED
        }

        self.assertTrue(any("no-such-class-anywhere" in edge_id for edge_id in unused))

    def test_a_declared_but_never_consumed_token_is_unused(self):
        unused = {e.from_id for e in self.graph.edges if e.status is Status.UNUSED}

        self.assertIn("css_token_def:token:--dead-token", unused)

    def test_a_consumed_token_is_connected(self):
        connected = {e.to_id for e in self.graph.edges if e.status is Status.CONNECTED}

        self.assertIn("css_token_def:token:--used-token", connected)

    def test_a_utility_build_class_is_never_reported_unresolved(self):
        unresolved = {
            e.from_id for e in self.graph.edges if e.status is Status.UNRESOLVED
        }

        self.assertFalse(any("bg-slate-900" in edge_id for edge_id in unresolved))

    def test_a_runtime_selector_is_uncertain_and_never_flagged(self):
        dynamic = [s for s in self.by_kind.get("dom_selector", []) if s.label == "<dynamic>"]

        self.assertTrue(dynamic)
        self.assertTrue(all(s.status is Status.UNCERTAIN for s in dynamic))
        self.assertNotIn("<dynamic>", {s.label for s in self.by_kind.get("multi_writer_element", [])})

    def test_url_and_view_kinds_are_still_never_claimed_unused(self):
        claimed = [
            s for s in self.graph.symbols
            if s.status is Status.UNUSED and s.kind in ("url", "view")
        ]

        self.assertEqual(claimed, [])


class OneRowPerSymbolTests(SimpleTestCase):
    """A symbol id names one symbol, or every count that walks the list is wrong.

    On the reference project 7,009 of 60,240 rows were duplicates - 11,199 `dom_selector`
    ids and 2,518 `dom_attr` ids appearing more than once. The map keys nodes by id so
    nothing was drawn wrong, which is exactly why it went unnoticed: the totals in the
    console, the backlog and every per-kind figure were inflated, and the extra rows were
    paid for in bytes on every render.

    Two causes, both here. The evidence pass appends `:evidence` to a `sub` that may
    already end in it - `class:string:evidence:evidence` - and a third source of
    selectors was concatenated onto the first two without being deduped against them,
    which also dropped the owner and the note from the copy that won.
    """

    def setUp(self):
        self.graph = run_scan(
            urlconf_module="seamcheck.tests.fixtures.fixture_urls",
            js_entry_files=[str(FIXTURES / "fixture_dom_multiwriter_a.js")],
            js_extra_files=[str(FIXTURES / "fixture_dom_multiwriter_b.js"),
                            str(FIXTURES / "fixture_dom_single_writer.js")],
            js_project_root=str(FIXTURES),
            template_files=[str(FIXTURES / "fixture_dom_template.html")],
            css_files=[str(FIXTURES / "fixture_dom.css")],
        )

    def test_no_symbol_id_appears_twice(self):
        seen = collections.Counter(s.id for s in self.graph.symbols)
        repeated = {i: n for i, n in seen.items() if n > 1}
        self.assertEqual(repeated, {}, f"{len(repeated)} ids appear more than once")

    def test_no_sub_carries_evidence_twice(self):
        doubled = [s.id for s in self.graph.symbols if ":evidence:evidence" in s.sub]
        self.assertEqual(doubled, [])
