"""Re-shoot docs/images/function.png - one function's world, and what it costs.

    python tools/shot_function.py docs/images/function.png

Headless, device scale 1, no trace: a headed run of a real project's map at scale 2 has
taken a laptop down. The graph below is a fixture, not a scan of anyone's repository, so
the picture can be regenerated by anyone and names nobody's code.
"""
import pathlib
import sys
import tempfile

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
import django
from django.conf import settings

settings.configure(INSTALLED_APPS=["seamcheck"], DATABASES={}, USE_TZ=True)
django.setup()

from playwright.sync_api import sync_playwright  # noqa: E402

from seamcheck.console import build_console  # noqa: E402
from seamcheck.graph import Edge, Graph, Status, Symbol  # noqa: E402
from seamcheck.mapdata import build_map  # noqa: E402
from seamcheck.renderers.map_html import render_document  # noqa: E402
from seamcheck.report import build_report  # noqa: E402


def symbol(kind, label, status=Status.CONNECTED, file="app/views.py", owner=""):
    return Symbol(id=f"{kind}:{label}", kind=kind, label=label, sub="", file=file,
                  line=12, status=status, snippet=f"{kind} {label}", chain=[label],
                  note="", owner=owner)


JS = "static/js/orders.js"
SERVICE = "app/services.py"
symbols = [
    symbol("fetch_target", "/api/push/", file=JS, owner="sendPush"),
    symbol("url", "api/push/", file="app/urls.py"),
    symbol("view", "submit_push", owner="submit_push"),
    symbol("redis_key_use", "user:{id}:pushes", owner="record"),
    symbol("redis_key_use", "user:{id}:stats", owner="record"),
    symbol("redis_key_use", "user:{id}:streak", file=SERVICE, owner="touch"),
    # The one that does not belong: a write to Postgres from a handler that is meant to
    # be Redis-only. This is the shape the cost line exists to make obvious.
    symbol("db_table_use", "orders_push", file=SERVICE, owner="touch"),
    symbol("celery_task", "tasks.settle", file=SERVICE, owner="record"),
]
edges = [
    Edge(from_id="fetch_target:/api/push/", to_id="url:api/push/", status=Status.CONNECTED),
    Edge(from_id="url:api/push/", to_id="view:submit_push", status=Status.CONNECTED),
    Edge(from_id="view:submit_push", to_id="redis_key_use:user:{id}:pushes",
         status=Status.CONNECTED),
]
graph = Graph(symbols=symbols, edges=edges)
pages = {"orders": {JS, "app/views.py", "app/urls.py", SERVICE}}
CALLS = {"submit_push": ["record"], "record": ["touch"]}
DEFINED = {"submit_push": "app/views.py", "record": SERVICE, "touch": SERVICE,
           "sendPush": JS}
document = render_document(
    build_map(graph, pages, git_sha="0" * 12, calls=CALLS, defined=DEFINED),
    console=build_console(graph, build_report(graph=graph, diff=None, entries=[],
                                              git_sha="0" * 12)),
)
path = pathlib.Path(tempfile.mkdtemp()) / "map.html"
path.write_text(document.single_file(), encoding="utf-8")

out = pathlib.Path(sys.argv[1])
with sync_playwright() as playwright:
    browser = playwright.chromium.launch()
    page = browser.new_page(viewport={"width": 1120, "height": 700}, device_scale_factor=1)
    page.goto(path.as_uri(), wait_until="load")
    page.wait_for_function("() => !!PAGES[Number(document.getElementById('pg').value)].nodes")
    page.wait_for_timeout(500)
    # Light one wire the way a reader does - through the map's own "open this result",
    # not a synthetic hover: the panel sits over the canvas and intercepts the pointer.
    # The map opens on Overview; the pickers belong to the map.
    if page.get_attribute("#menubtn", "aria-expanded") != "true":
        page.click("#menubtn")
    page.click('#nav .nv[data-key="map"]')
    page.wait_for_timeout(600)
    page.evaluate("() => pickFunction('submit_push')")
    page.wait_for_timeout(1200)
    page.screenshot(path=str(out))
    browser.close()
print(out, out.stat().st_size, "bytes")
