"""Re-shoot docs/images/stores.png - the store band's lanes, and the deployables below.

    python tools/shot_stores.py docs/images/stores.png

Headless, one browser, no trace. The graph is a fixture rather than a scan of anyone's
repository, so the picture can be regenerated by anyone and names nobody's code. It
shows the two things the band exists for: three stores side by side, each with its
own oracle badge, and below them two deployables side by side, each in its language.
"""
import pathlib
import sys
import tempfile

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
import django
from django.conf import settings

settings.configure(INSTALLED_APPS=["seamcheck"], DATABASES={}, USE_TZ=True)
django.setup()

from playwright.sync_api import sync_playwright  # noqa: E402

from seamcheck.console import build_console  # noqa: E402
from seamcheck.graph import Edge, Graph, Status, Symbol  # noqa: E402
from seamcheck.mapdata import build_map  # noqa: E402
from seamcheck.renderers.map_html import render_document  # noqa: E402
from seamcheck.report import build_report  # noqa: E402
from seamcheck.services import Service, ServiceMap  # noqa: E402

OK, DEAD, UNUSED, UNSURE = (Status.CONNECTED, Status.UNRESOLVED, Status.UNUSED,
                            Status.UNCERTAIN)


def symbol(kind, label, file, status=OK):
    return Symbol(id=f"{kind}:{label}", kind=kind, label=label, sub="", file=file,
                  line=1, status=status, snippet=f"{kind} {label}", chain=[label], note="")


SQL, API, VIEWS, CACHE = ("supabase/migrations/001_orders.sql", "apps/api/src/orders.ts",
                          "services/web/app/views.py", "services/web/app/cache.py")
symbols = [
    # Postgres: declared in a migration, read from the TypeScript service.
    symbol("db_table", "orders", SQL), symbol("db_table", "customers", SQL, UNUSED),
    symbol("db_column", "orders.id", SQL), symbol("db_column", "orders.total", SQL),
    symbol("db_column", "orders.placed_at", SQL),
    symbol("db_column", "customers.id", SQL, UNSURE),
    symbol("db_column", "customers.email", SQL, UNSURE),
    symbol("db_policy", "orders", SQL, DEAD),
    symbol("db_table_use", "orders", API), symbol("db_table_use", "order_lines", API, DEAD),
    symbol("db_column_use", "orders.id", API), symbol("db_column_use", "orders.total", API),
    symbol("db_column_use", "orders.placed_at", API),
    symbol("db_column_use", "order_lines.sku", API, UNSURE),
    symbol("db_column_use", "order_lines.qty", API, UNSURE),
    # Redis: nothing declares a key, so the lane can only pair.
    symbol("redis_key", "session:*:last_seen", CACHE, UNUSED),
    symbol("redis_key", "user:*:order_count", CACHE, DEAD),
    symbol("redis_key", "user:*:stats", CACHE),
    symbol("redis_key_use", "session:*:last_seen", VIEWS),
    symbol("redis_key_use", "user:*:order_count", VIEWS),
    symbol("redis_key_use", "user:*:stat", VIEWS, UNSURE),
    symbol("redis_key_use", "user:*:stats", VIEWS),
    symbol("redis_key_use", "user:*:stats", "services/web/app/tasks.py"),
    symbol("redis_ttl", "session:*:last_seen", CACHE, DEAD),
    # Firebase: rules in the repo, collections named from the browser.
    symbol("firestore_rule", "profiles", "firestore.rules"),
    symbol("firestore_rule", "devices", "firestore.rules"),
    symbol("firestore_rule", "receipts", "firestore.rules", UNUSED),
    symbol("firestore_collection", "profiles", "apps/web/src/push.js"),
    symbol("firestore_collection", "devices", "apps/web/src/push.js"),
    symbol("firestore_collection", "push_tokens", "apps/web/src/push.js", DEAD),
    # Reached without a browser: one TypeScript service, one Python service.
    symbol("job", "acme", "apps/api/src/jobs.ts", UNSURE),
    symbol("job", "reconcile-payment", "apps/api/src/jobs.ts", UNSURE),
    symbol("job", "send-receipt", "apps/api/src/jobs.ts"),
    symbol("job_enqueue", "send-receipt", "apps/api/src/queue.ts"),
    symbol("job_enqueue", "reconcile-payments", "apps/api/src/queue.ts", DEAD),
    symbol("env_read", "2 of 2 configuration keys read here", "apps/api/src/config.ts",
           UNSURE),
    symbol("celery_task", "tasks.rebuild_catalog", "services/web/app/tasks.py", UNSURE),
    symbol("celery_task", "tasks.send_digest", "services/web/app/tasks.py", UNSURE),
    symbol("celery_task", "tasks.settle_payouts", "services/web/app/tasks.py", UNSURE),
    symbol("celery_schedule", "config.tasks.rebuild_catalog", "services/web/config.py"),
    symbol("celery_schedule", "config.tasks.send_digest", "services/web/config.py"),
    symbol("celery_schedule", "config.tasks.settle_payments", "services/web/config.py",
           DEAD),
]
edges = [
    Edge(from_id=a, to_id=b, status=OK) for a, b in (
        ("db_table:orders", "db_table_use:orders"),
        ("db_column:orders.total", "db_column_use:orders.total"),
        ("db_column:orders.placed_at", "db_column_use:orders.placed_at"),
        ("redis_key:user:*:stats", "redis_key_use:user:*:stats"),
        ("redis_key:session:*:last_seen", "redis_key_use:session:*:last_seen"),
        ("firestore_rule:profiles", "firestore_collection:profiles"),
        ("firestore_rule:devices", "firestore_collection:devices"),
        ("job:send-receipt", "job_enqueue:send-receipt"),
        ("celery_task:tasks.rebuild_catalog", "celery_schedule:config.tasks.rebuild_catalog"),
        ("celery_task:tasks.send_digest", "celery_schedule:config.tasks.send_digest"),
    )
]
services = ServiceMap([
    Service(name="@acme/api", root="apps/api", language="TypeScript",
            evidence=["package.json"], deployable=True),
    Service(name="web", root="services/web", language="Python",
            evidence=["pyproject.toml"], deployable=True),
])
graph = Graph(symbols=symbols, edges=edges)
document = render_document(
    build_map(graph, {}, git_sha="0" * 12, services=services),
    console=build_console(graph, build_report(graph=graph, diff=None, entries=[],
                                              git_sha="0" * 12)),
)
path = pathlib.Path(tempfile.mkdtemp()) / "map.html"
path.write_text(document.single_file(), encoding="utf-8")

out = pathlib.Path(sys.argv[1])
with sync_playwright() as playwright:
    browser = playwright.chromium.launch()
    page = browser.new_page(viewport={"width": 1440, "height": 900}, device_scale_factor=2)
    page.goto(path.as_uri(), wait_until="load")
    if page.get_attribute("#menubtn", "aria-expanded") != "true":
        page.click("#menubtn")
    page.click('#nav .nv[data-key="map"]')
    page.wait_for_selector("#cv .nd", state="attached")
    page.wait_for_timeout(800)
    page.screenshot(path=str(out))
    browser.close()
print(out, out.stat().st_size, "bytes")
