"""Re-shoot docs/images/tiers.png - the four tiers with one chain lit.

    python tools/shot_tiers.py docs/images/tiers.png

Headless, device scale 1, no trace: a headed run of a real project's map at scale 2 has
taken a laptop down. The graph below is a fixture, not a scan of anyone's repository, so
the picture can be regenerated by anyone and names nobody's code.
"""
import pathlib
import sys
import tempfile

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
import django
from django.conf import settings

settings.configure(INSTALLED_APPS=["seamcheck"], DATABASES={}, USE_TZ=True)
django.setup()

from playwright.sync_api import sync_playwright  # noqa: E402

from seamcheck.console import build_console  # noqa: E402
from seamcheck.graph import Edge, Graph, Status, Symbol  # noqa: E402
from seamcheck.mapdata import build_map  # noqa: E402
from seamcheck.renderers.map_html import render_document  # noqa: E402
from seamcheck.report import build_report  # noqa: E402


def symbol(kind, label, status=Status.CONNECTED, file="app/views.py", sub=""):
    return Symbol(id=f"{kind}:{label}", kind=kind, label=label, sub=sub, file=file,
                  line=1, status=status, snippet=f"{kind} {label}", chain=[label], note="")


JS = "static/js/orders.js"
symbols = [
    symbol("fetch_target", "/api/orders/", file=JS),
    symbol("fetch_target", "/api/gone/", Status.UNRESOLVED, JS),
    symbol("url", "api/orders/", file="app/urls.py"),
    symbol("view", "orders", file="app/views.py"),
    symbol("redis_key", "cart:{user}:items", file="app/views.py"),
]
edges = [
    Edge(from_id="fetch_target:/api/orders/", to_id="url:api/orders/",
         status=Status.CONNECTED),
    Edge(from_id="url:api/orders/", to_id="view:orders", status=Status.CONNECTED),
    Edge(from_id="view:orders", to_id="redis_key:cart:{user}:items",
         status=Status.CONNECTED),
]
graph = Graph(symbols=symbols, edges=edges)
pages = {"orders": {JS}}
document = render_document(
    build_map(graph, pages, git_sha="0" * 12),
    console=build_console(graph, build_report(graph=graph, diff=None, entries=[],
                                              git_sha="0" * 12)),
)
path = pathlib.Path(tempfile.mkdtemp()) / "map.html"
path.write_text(document.single_file(), encoding="utf-8")

out = pathlib.Path(sys.argv[1])
with sync_playwright() as playwright:
    browser = playwright.chromium.launch()
    page = browser.new_page(viewport={"width": 1120, "height": 700}, device_scale_factor=1)
    page.goto(path.as_uri(), wait_until="load")
    page.wait_for_function("() => !!PAGES[Number(document.getElementById('pg').value)].nodes")
    page.wait_for_timeout(500)
    # Light one wire the way a reader does - through the map's own "open this result",
    # not a synthetic hover: the panel sits over the canvas and intercepts the pointer.
    page.evaluate("""() => {
      const i = PAGES.findIndex(p => (p.title || p.page || '').includes('orders'));
      return jumpTo('fetch_target:/api/orders/', i < 0 ? current : i);
    }""")
    page.wait_for_timeout(800)
    page.screenshot(path=str(out))
    browser.close()
print(out, out.stat().st_size, "bytes")
